---
name: 🚀 Feature Request
description: Suggest an idea for the MCP AWS Provider Docs server
title: "(module name): (short issue description)"
labels: [feature, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you are proposing for the MCP server, AWS provider, or Terragrunt documentation.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve for users of the MCP server or Terragrunt documentation?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Suggest how to implement the addition or change. Please include prototype/workaround/sketch/reference implementation.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: Any alternative solutions or features you considered, a more detailed explanation, stack traces, related issues, links for context, etc.
    validations:
      required: false
  - type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: I may be able to implement this feature request
          required: false
        - label: This feature might incur a breaking change
          required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.github.io/code-of-conduct).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
