---
name: 🔖 Assign labels on PR
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
defaults:
  run:
    shell: bash
permissions:
  contents: write
  pull-requests: write
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          configuration-path: .github/labeler.yml
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "XS",
              "15": "S",
              "30": "M",
              "50": "L",
              "250": "Too Large"
            }
